# Generated by Django 4.2.6 on 2023-10-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='dafault_pic.png', upload_to='profile_picture'),
        ),
    ]
